### ISSUE TITLE
linking to a badge profile without being signed into Canvas

### ISSUE THREAD

**Issue by NoisyText** [whitmer/canvabadges#13]
Is there a way to present the information without having to have a person logged in first? 

I would like to show off some of the badges to people who are not in the course. The idea would be that I could link to the badge's information/profile and people could see the badge and the requirements for the badge. As far as I can tell this is not possible in the system right now.

**Comment by whitmer** [comment]
If you have set up your own organization then you can do it (i.e. https://www.canvabadges.org/_emmanuel/badges/public?this_org_only=1), and see a brief summary of all the badges that have been marked to be shared in the organization's directory. Linking to a specific badge from there wouldn't be too hard, there's already technically a URL for it (https://www.canvabadges.org/_emmanuel/badges/criteria/4490/2cf5efcb52b12a88ec25abe314ad4b0c)..

**Comment by whitmer** [comment]
Just pushed a commit that's one step closer. The public badges for an org page (i.e. https://www.canvabadges.org/_emmanuel/badges/public?this_org_only=1) now links the badge image to the badge details page. I'll look into adding a link to the badge config page as well.

**Comment by whitmer** [comment]
..and now when you set a badge to show up in the organization's public directory and save, you'll see a badge description link next to that checkbox whenever you load the badge settings. That should do it!

**Comment by NoisyText** [comment]
That's awesome! Thanks :-)
